version: '1.0.{build}'
image: Visual Studio 2017
clone_depth: 10
skip_tags: true

# branches:
#   only:
#   - master
#   - develop

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module Pester -Scope CurrentUser -SkipPublisherCheck -Force | Out-Null
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force | Out-Null
build: off

test_script:
- ps: |
      Invoke-Pester -Script C:\projects\scriptanalyzer-practiceandstyle\test* -OutputFile .\nunit-results.xml -OutputFormat NUnitXML

      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit-results.xml))
